apiVersion: v1
kind: Service
metadata:
  name: jenkins-agent
  labels:
    app: jenkins-agent
spec:
  ports:
  - port: 22
    name: sshd
  clusterIP: None
  selector:
    app: jenkins-agent
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: jenkins-agent
spec:
  serviceName: jenkins-agent
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins-agent
    spec:
      securityContext:
        fsGroup: 1000

      initContainers:
      - name: jenkins-agent-init
        image: openjdk:8-jre-alpine
        imagePullPolicy: IfNotPresent
        command: ['sh', '/tmp/bootstrap/jenkins-agent-bootstrap.sh']
        env:
        - name: JENKINS_URL
          value: http://jenkins-master:8080
        - name: JENKINS_LABEL
          value: stateful
        volumeMounts:
        - name: jenkins-ssh-key
          mountPath: /tmp/ssh/
        - name: jenkins-agent-bootstrap
          mountPath: /tmp/bootstrap/

      containers:
      - name: jenkins-agent
        image: jenkinsci/ssh-slave
        ports:
        - containerPort: 22
        env:
        - name: JENKINS_SLAVE_SSH_PUBKEY
          valueFrom:
            secretKeyRef:
              name: jenkins-ssh-key
              key: jenkins_ssh.pub
        volumeMounts:
        - name: jenkins-agent-pv
          mountPath: /mnt/pv

      volumes:
      - name: jenkins-ssh-key
        secret:
          secretName: jenkins-ssh-key
      - name: jenkins-agent-bootstrap
        configMap:
          name: jenkins-agent-bootstrap

  volumeClaimTemplates:
  - metadata:
      name: jenkins-agent-pv
    spec:
      storageClassName: default
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
